---
- name: Wait for cloud-init to complete
  command: cloud-init status --wait
  changed_when: false

- name: Create password file
  copy:
    content: "PASSWORD='{{ vault_lucidlink_password }}'"
    dest: "/root/.{{ service_name }}.pwd"
    owner: root
    group: root
    mode: '0400'
  no_log: true

- name: Create LucidLink service file
  template:
    src: lucidlink.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Force systemd reload
  systemd:
    daemon_reload: yes

- name: Enable and start LucidLink service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
